version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped
    container_name: treasurehunt-api
    ports:
      - '3333:3333'

  nginx:
    build:
      context: .
      dockerfile: ./.deployment/nginx/Dockerfile
    container_name: treasurehunt-nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    volumes:
      - ./dist/apps/app:/var/www/treasure-hunt.app
