name: Deployment 🚀
on:
  push:
    branches:
      - master

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: npm ci

      - name: build
        run: |
          npm run nx build api -- --configuration=production
          npm run nx build app -- --configuration=production

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t treasurehunt/nginx:latest . -f ./.deployment/nginx/Dockerfile
          docker build -t treasurehunt/api:latest . -f ./apps/api/Dockerfile

      - name: Push to docker registry
        uses: actions-hub/docker@master
        with:
          args: push treasurehunt/nginx:latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ DROPLET_IP }}
          username: deployer
          password: ${{ secrets.SSH_DEPLOYER }}
          port: 22
          script: |
            docker-compose -f /var/www/treasure-hunt.app/docker-compose.yml up -d --force-recreate
